ingress:
  enabled: true
  ingressClassName: traefik
  pathType: Prefix
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: plex.essenov.com
      paths:
        - /

# -- PMS configuration
pms:
  storageClassName: local-path
  configStorage: 2Gi
  configExistingClaim: "plex-config"

# -- Additional volume mounts for media
extraVolumeMounts:
  - name: media
    mountPath: /media

# -- Additional volumes using PersistentVolumeClaims
extraVolumes:
  - name: media
    persistentVolumeClaim:
      claimName: plex-media

# -- Enable devices to be discoverable
hostNetwork: true

env:
  TZ: "Europe/Sofia"