apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-content-pv
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
  - ReadOnlyMany
  hostPath:
    path: /home/essenov/web-content  # Change this to your local drive path
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-content-pvc
  namespace: nginx-app
spec:
  storageClassName: local
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-content-pv
