---
# PV for Plex config
# FOLDER TO CREATE: /var/lib/plex/config
# Store Plex media server database and settings
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /var/lib/plex/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: plex
          operator: In
          values:
          - "true"
---
# PV for Plex transcode
# FOLDER TO CREATE: /var/lib/plex/transcode
# Temporary storage for video transcoding
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-transcode-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /var/lib/plex/transcode
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: plex
          operator: In
          values:
          - "true"
---
# PV for Plex media
# Your actual media files (movies, shows, music)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: plex
          operator: In
          values:
          - "true"
