apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iessenov/gitops
    targetRevision: main
    path: platform/ingress-nginx/overlays/dev
    kustomize:
      enableHelm: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
