apiVersion: v1
kind: ConfigMap
metadata:
  name: create-databases-sql
data:
  create-databases.sql: |
    CREATE DATABASE app2db;
    CREATE DATABASE app3db;

    GRANT ALL PRIVILEGES ON DATABASE app2db TO app2user;
    GRANT ALL PRIVILEGES ON DATABASE app3db TO app3user;